package src.hxyarn.compiler;

class Token {
	public var type:TokenType;
	public var lexeme:String;
	public var literal:Dynamic;
	public var line:Int;
	public var nodeName:String;

	public function new(type:TokenType, lexeme:String, literal:Dynamic, line:Int, nodeName:String) {
		this.type = type;
		this.lexeme = lexeme;
		this.literal = literal;
		this.line = line;
		this.nodeName = nodeName;
	}

	public function toString():String {
		return '${type.getName()} $lexeme $literal';
	}
}

enum TokenType {
	INDENT;
	DEDENT;
	WS;
	NEWLINE;
	ID;
	BODY_START;
	HEADER_DELIMITER;
	HASHTAG;
	REST_OF_LINE;
	HEADER_NEWLINE;
	COMMENT;
	BODY_WS;
	BODY_NEWLINE;
	BODY_COMMENT;
	BODY_END;
	SHORTCUT_ARROW;
	COMMAND_START;
	OPTION_START;
	FORMAT_FUNCTION_START;
	BODY_HASHTAG;
	TEXT_NEWLINE;
	TEXT_HASHTAG;
	TEXT_EXPRESSION_START;
	TEXT_COMMAND_START;
	TEXT_FORMAT_FUNCTION_START;
	TEXT_COMMENT;
	TEXT;
	TEXT_FRAG;
	TEXT_COMMANDHASHTAG_WS;
	TEXT_COMMANDHASHTAG_COMMENT;
	TEXT_COMMANDHASHTAG_COMMAND_START;
	TEXT_COMMANDHASHTAG_HASHTAG;
	TEXT_COMMANDHASHTAG_NEWLINE;
	TEXT_COMMANDHASHTAG_ERROR;
	HASHTAG_WS;
	HASHTAG_TAG;
	HASHTAG_TEXT;
	FORMAT_FUNCTION_WS;
	FORMAT_FUNCTION_ID;
	FORMAT_FUNCTION_NUMBER;
	FORMAT_FUNCTION_EXPRESSION_START;
	FORMAT_FUNCTION_EQUALS;
	FORMAT_FUNCTION_STRING;
	FORMAT_FUNCTION_END;
	EXPR_WS;
	KEYWORD_TRUE;
	KEYWORD_FALSE;
	KEYWORD_NULL;
	OPERATOR_ASSIGNMENT;
	OPERATOR_LOGICAL_LESS_THAN_EQUALS;
	OPERATOR_LOGICAL_GREATER_THAN_EQUALS;
	OPERATOR_LOGICAL_EQUALS;
	OPERATOR_LOGICAL_LESS;
	OPERATOR_LOGICAL_GREATER;
	OPERATOR_LOGICAL_NOT_EQUALS;
	OPERATOR_LOGICAL_AND;
	OPERATOR_LOGICAL_OR;
	OPERATOR_LOGICAL_XOR;
	OPERATOR_LOGICAL_NOT;
	OPERATOR_MATHS_NEGATIVE;
	OPERATOR_MATHS_ADDITION_EQUALS;
	OPERATOR_MATHS_SUBTRACTION_EQUALS;
	OPERATOR_MATHS_MULTIPLICATION_EQUALS;
	OPERATOR_MATHS_MODULUS_EQUALS;
	OPERATOR_MATHS_DIVISION_EQUALS;
	OPERATOR_MATHS_ADDITION;
	OPERATOR_MATHS_SUBTRACTION;
	OPERATOR_MATHS_MULTIPLICATION;
	OPERATOR_MATHS_DIVISION;
	OPERATOR_MATHS_MODULUS;
	LPAREN;
	RPAREN;
	COMMA;
	STRING;
	FUNC_ID;
	EXPRESSION_END;
	EXPRESSION_COMMAND_END;
	VAR_ID;
	NUMBER;
	COMMAND_WS;
	COMMAND_IF;
	COMMAND_ELSEIF;
	COMMAND_ELSE;
	COMMAND_SET;
	COMMAND_ENDIF;
	COMMAND_CALL;
	COMMAND_END;
	COMMAND_TEXT_END;
	COMMAND_EXPRESSION_START;
	COMMAND_TEXT;
	OPTION_NEWLINE;
	OPTION_WS;
	OPTION_END;
	OPTION_DELIMIT;
	OPTION_EXPRESSION_START;
	OPTION_FORMAT_FUNCTION_START;
	OPTION_TEXT;
	OPTION_ID_WS;
	OPTION_ID;
	FORMAT_FUNCTIONEND;
	EOF;
}
